default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: desenv
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  schema_search_path: infografico_interativo

test:
  <<: *default
  database: n_definido

production:
  <<: *default
  database: pd
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  schema_search_path: infografico_interativo